# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/playitem_imgs/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('zodiac_choice', models.PositiveSmallIntegerField(choices=[(1, 'Тематика 1'), (2, 'Космос'), (3, 'Романтика')])),
            ],
        ),
        migrations.AddField(
            model_name='playitem',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_plitem', to='domeplaylist.PlayList'),
        ),
    ]
