# Generated by Django 2.0.1 on 2018-01-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domeplaylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayItem',
            new_name='Track',
        ),
    ]
