# Generated by Django 2.0.1 on 2018-02-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domeplaylist', '0002_auto_20180120_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/track_imgs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_track', to='domeplaylist.PlayList'),
        ),
    ]
