# Generated by Django 2.0.1 on 2018-02-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domeplaylist', '0003_auto_20180223_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
