# Generated by Django 2.0.1 on 2018-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domeplaylist', '0004_playlist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='theme',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Тематика 1'), (2, 'Космос'), (3, 'Романтика')], null=True),
        ),
    ]
